apiVersion: 1

datasources:
- name: influxdb
  type: influxdb
  access: proxy
  url: http://127.0.0.1:{{MFADMIN_INFLUXDB_HTTP_PORT}}
  access: proxy
  database: metrics
  isDefault: true
  editable: false
- name: es_nginx
  type: elasticsearch
  access: proxy
  database: "nginx-*"
  url: http://127.0.0.1:{{MFADMIN_ELASTICSEARCH_HTTP_PORT}}
  jsonData:
    timeField: "@timestamp"
    esVersion: 60
